"""add vocab synonyms and notes

Revision ID: 49d0ed3a8eea
Revises: 2e839a2270b1
Create Date: 2026-05-01 21:22:14.846453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d0ed3a8eea'
down_revision = '2e839a2270b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gerengvocab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synonyms', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gerengvocab', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('synonyms')

    # ### end Alembic commands ###
